apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: logstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator
          image: log-generator:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: log-generator-config
