apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: logstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
    spec:
      containers:
        - name: log-processor
          image: log-processor:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: log-processor-config
            - secretRef:
                name: opensearch-credentials
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
