apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: log-processor-hpa
  namespace: logstream
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-processor
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
